include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for youtubeUnblock
LUCI_DEPENDS:=+luci-base

PKG_LICENSE:=GPL
PKG_MAINTAINER:=Vadim Vetrov <vetrovvd@gmail.com>

include ./luci.mk

# call BuildPackage - OpenWrt buildroot signature
