include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for youtubeUnblock
LUCI_DEPENDS:=+luci-base
LUCI_BASENAME:=youtubeUnblock

PKG_LICENSE:=GPL
PKG_MAINTAINER:=Vadim Vetrov <vetrovvd@gmail.com>

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
