#!/bin/sh /etc/rc.common

# Thanks @spvkgn for reference: https://github.com/spvkgn/ByeDPI-OpenWrt/blob/main/byedpi/files/byedpi.init


START=91
USE_PROCD=1
# PROCD_DEBUG=1
PROG=/usr/bin/youtubeUnblock

UCI_ARGS=""

# If you have troubles with uci, pass args here
POST_ARGS=""

read_uci_args() {
	local value
	config_get value "$1" "args"
	UCI_ARGS="$value" 
}

# Openwrt procd script: https://openwrt.org/docs/guide-developer/procd-init-script-example
# The program should be put into /usr/bin/
# This file should be put into /etc/init.d/

start_service() {
	config_load youtubeUnblock
	read_uci_args youtubeUnblock

	echo "youtubeUnblock is running as: '$PROG $UCI_ARGS $POST_ARGS'"

	procd_open_instance 'youtubeUnblock'
	procd_set_param command $PROG $UCI_ARGS $POST_ARGS
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
        procd_add_reload_trigger "youtubeUnblock"
}

reload_service() {
        stop
        start
}
