#!/bin/sh /etc/rc.common
# shellcheck disable=SC3043,SC2034

START=95
USE_PROCD=1
PROCD_DEBUG=1
PROG=/usr/bin/ytunblock

boot() {
	ubus -t 30 wait_for network.interface network.loopback 2>/dev/null
	rc_procd start_service
}

start_service() {
	config_load ytunblock

	local num
	config_get num main num

	procd_open_instance
	procd_set_param command $PROG $num
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param respawn
	procd_close_instance
}
